# Generated by Django 4.0.4 on 2022-04-12 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumb0', models.ImageField(blank=True, upload_to='')),
                ('subHeading1', models.CharField(blank=True, max_length=100)),
                ('text1', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('subHeading2', models.CharField(blank=True, max_length=100)),
                ('text2', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('subHeading3', models.CharField(blank=True, max_length=100)),
                ('text3', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('subHeading4', models.CharField(blank=True, max_length=100)),
                ('text4', models.TextField(blank=True)),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('subHeading5', models.CharField(blank=True, max_length=100)),
                ('text5', models.TextField(blank=True)),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('subHeading6', models.CharField(blank=True, max_length=100)),
                ('text6', models.TextField(blank=True)),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('subHeading7', models.CharField(blank=True, max_length=100)),
                ('text7', models.TextField(blank=True)),
                ('image7', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='carr', max_length=25)),
            ],
        ),
    ]
